# Generated by Django 4.1.4 on 2022-12-26 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='purchaser',
            new_name='owner',
        ),
    ]
