# Generated by Django 4.1.4 on 2022-12-26 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_rename_purchaser_book_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='page',
        ),
    ]
